### PR TITLE
Fix click handling for `<LinkTo />` component

### LINKED ISSUE #12: Possibly broken <LinkTo>
While I was working on ember-engines, I found out that LinkTo wouldn't work correctly. When clicked, the transition wouldn't fire.
https://github.com/ember-engines/ember-engines/pull/798/files#diff-a450f3a85dfbf538ccb97a9f73a2e49359d87c3c09e6fe3842adf909f1b74809R42

I think it might be because `_generateTransition` creates a callback which is never called.
https://github.com/emberjs/ember-legacy-built-in-components/blob/main/addon/components/link-to.ts#L810

The link-to implementation in ember 3.28 on the other hand passes the generated callback to `flaggedInstrument` which fires the transition.
https://github.com/emberjs/ember.js/blob/v3.28.8/packages/%40ember/-internals/glimmer/lib/components/-link-to.ts#L767

### PR DESCRIPTION
**Pull request by SergeAstapov**
Fixes #12

### CODE REVIEW

File: addon/components/link-to.ts [hunk 1]
```diff
@@ -309,7 +309,7 @@ const LinkComponent = EmberComponent.extend({
     @property disabledWhen
     @public
   */
-  disabledWhen: UNDEFINED,
+  disabledWhen: undefined,
```
Comment (SergeAstapov) [inline addon/components/link-to.ts:312]: [this check](https://github.com/emberjs/ember-legacy-built-in-components/blob/main/addon/components/link-to.ts#L945) was making every link disabled hence clicks didn't result in transitions

File: addon/components/link-to.ts [hunk 2]
```diff
@@ -820,14 +820,12 @@ const LinkComponent = EmberComponent.extend({
...
 
-    return () => {
-      payload.transition = routing.transitionTo(
-        qualifiedRouteName,
-        models,
-        queryParams,
-        shouldReplace
-      );
-    };
+    payload.transition = routing.transitionTo(
```
Comment (SergeAstapov) [inline addon/components/link-to.ts:823]: this function had to return callback when was wrapped into `flaggedInstrument` but now we just need to invoke `transitionTo`
